#!/bin/sh
set -eu

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

SYSTEM_TYPE="aarch64-darwin"
FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"

export NIXPKGS_ALLOW_UNFREE=1

printf '%b\n' "${YELLOW}Starting build...${NC}"
nix --extra-experimental-features 'nix-command flakes' build ".#$FLAKE_SYSTEM" "$@"

printf '%b\n' "${YELLOW}Cleaning up...${NC}"
unlink ./result

printf '%b\n' "${GREEN}Build complete!${NC}"
